import { useEffect, useMemo, useState } from 'react';

const monthNames = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'
];

const weekdayLabels = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

function formatDateKey(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function addDays(date, amount) {
  const next = new Date(date);
  next.setDate(next.getDate() + amount);
  return next;
}

function buildInitialTasks() {
  const saved = localStorage.getItem('monthly-todo-tasks');
  return saved ? JSON.parse(saved) : [];
}

function App() {
  const today = new Date();
  const [currentMonth, setCurrentMonth] = useState(new Date(today.getFullYear(), today.getMonth(), 1));
  const [selectedDate, setSelectedDate] = useState(new Date(today.getFullYear(), today.getMonth(), today.getDate()));
  const [taskInput, setTaskInput] = useState('');
  const [tasks, setTasks] = useState(buildInitialTasks);

  useEffect(() => {
    localStorage.setItem('monthly-todo-tasks', JSON.stringify(tasks));
  }, [tasks]);

  const selectedKey = formatDateKey(selectedDate);

  const monthDays = useMemo(() => {
    const firstDay = new Date(currentMonth.getFullYear(), currentMonth.getMonth(), 1);
    const lastDay = new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 1, 0);
    const startPadding = firstDay.getDay();
    const totalCells = Math.ceil((startPadding + lastDay.getDate()) / 7) * 7;

    const cells = [];
    for (let index = 0; index < totalCells; index += 1) {
      const dayNumber = index - startPadding + 1;
      if (dayNumber <= 0 || dayNumber > lastDay.getDate()) {
        cells.push(null);
      } else {
        cells.push(new Date(currentMonth.getFullYear(), currentMonth.getMonth(), dayNumber));
      }
    }

    return cells;
  }, [currentMonth]);

  const selectedTasks = tasks.filter((task) => task.date === selectedKey);

  const addTask = () => {
    const text = taskInput.trim();
    if (!text) return;

    const newTaskId = crypto.randomUUID();
    const nextDate = addDays(selectedDate, 1);
    const nextDateKey = formatDateKey(nextDate);

    const task = {
      id: newTaskId,
      text,
      date: selectedKey,
      completed: false,
      linkedId: null,
      autoGenerated: false
    };

    const nextTask = {
      id: crypto.randomUUID(),
      text,
      date: nextDateKey,
      completed: false,
      linkedId: newTaskId,
      autoGenerated: true
    };

    setTasks((previousTasks) => [...previousTasks, task, nextTask]);
    setTaskInput('');
  };

  const toggleTask = (taskId) => {
    setTasks((previousTasks) =>
      previousTasks.map((task) =>
        task.id === taskId ? { ...task, completed: !task.completed } : task
      )
    );
  };

  const deleteTask = (taskId) => {
    setTasks((previousTasks) => {
      const targetTask = previousTasks.find((task) => task.id === taskId);
      if (!targetTask) return previousTasks;

      const autoLinkedTasks = previousTasks.filter(
        (task) => task.linkedId === taskId || task.id === targetTask.linkedId
      );

      return previousTasks.filter(
        (task) => task.id !== taskId && !autoLinkedTasks.some((linkedTask) => linkedTask.id === task.id)
      );
    });
  };

  const monthTaskSummary = (date) => {
    const key = formatDateKey(date);
    return tasks.filter((task) => task.date === key);
  };

  return (
    <div className="app-shell">
      <div className="todo-card">
        <header className="topbar">
          <button
            type="button"
            className="nav-button"
            onClick={() => setCurrentMonth(new Date(currentMonth.getFullYear(), currentMonth.getMonth() - 1, 1))}
          >
            ‹
          </button>

          <h1>
            {monthNames[currentMonth.getMonth()]} {currentMonth.getFullYear()}
          </h1>

          <button
            type="button"
            className="nav-button"
            onClick={() => setCurrentMonth(new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 1, 1))}
          >
            ›
          </button>
        </header>

        <div className="weekday-row">
          {weekdayLabels.map((label) => (
            <div key={label} className="weekday-name">{label}</div>
          ))}
        </div>

        <div className="calendar-grid">
          {monthDays.map((day, index) => {
            if (!day) {
              return <div key={`empty-${index}`} className="day empty" />;
            }

            const dayKey = formatDateKey(day);
            const isSelected = dayKey === selectedKey;
            const isToday = dayKey === formatDateKey(today);
            const dayTasks = monthTaskSummary(day);

            return (
              <button
                key={dayKey}
                type="button"
                className={`day-box ${isSelected ? 'selected' : ''} ${isToday ? 'today' : ''}`}
                onClick={() => setSelectedDate(day)}
              >
                <span className="day-number">{day.getDate()}</span>
                <div className="mini-task-wrap">
                  {dayTasks.slice(0, 3).map((task) => (
                    <span
                      key={`${dayKey}-${task.id}`}
                      className={`mini-dot ${task.completed ? 'done' : ''}`}
                      title={task.text}
                    />
                  ))}
                </div>
              </button>
            );
          })}
        </div>

        <section className="details-panel">
          <div className="detail-header">
            <h2>
              {selectedDate.toLocaleDateString(undefined, {
                weekday: 'long',
                month: 'long',
                day: 'numeric',
                year: 'numeric'
              })}
            </h2>
          </div>

          <div className="task-entry">
            <input
              type="text"
              value={taskInput}
              onChange={(event) => setTaskInput(event.target.value)}
              onKeyDown={(event) => {
                if (event.key === 'Enter') addTask();
              }}
              placeholder="Add a daily task..."
              aria-label="Add a daily task"
            />
            <button type="button" onClick={addTask} className="primary-button">
              Add
            </button>
          </div>

          <div className="task-list">
            {selectedTasks.length === 0 ? (
              <p className="empty-state">No tasks scheduled for this day.</p>
            ) : (
              selectedTasks.map((task) => (
                <div key={task.id} className={`task-item ${task.completed ? 'done' : ''}`}>
                  <button
                    type="button"
                    className="check-button"
                    onClick={() => toggleTask(task.id)}
                    aria-label={`Mark ${task.text} as complete`}
                  >
                    {task.completed ? '✓' : ''}
                  </button>

                  <span className="task-text">{task.text}</span>

                  <button
                    type="button"
                    className="delete-button"
                    onClick={() => deleteTask(task.id)}
                    aria-label={`Delete ${task.text}`}
                  >
                    ×
                  </button>
                </div>
              ))
            )}
          </div>
        </section>
      </div>
    </div>
  );
}

export default App;
