import { useEffect, useMemo, useState } from 'react';

const monthNames = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'
];
const weekdayLabels = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const STORAGE_KEY = 'monthly-todo-tasks';
const THEME_KEY = 'monthly-todo-theme';

function formatDateKey(date) {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
}

function addDays(date, amount) {
  const next = new Date(date);
  next.setDate(next.getDate() + amount);
  return next;
}

function makeId() {
  return globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`;
}

function readTasks() {
  try {
    const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]');
    return Array.isArray(saved) ? saved : [];
  } catch {
    return [];
  }
}

function App() {
  const today = new Date();
  const todayKey = formatDateKey(today);
  const [currentMonth, setCurrentMonth] = useState(new Date(today.getFullYear(), today.getMonth(), 1));
  const [selectedDate, setSelectedDate] = useState(today);
  const [taskInput, setTaskInput] = useState('');
  const [repeatDays, setRepeatDays] = useState('1');
  const [tasks, setTasks] = useState(readTasks);
  const [editingId, setEditingId] = useState(null);
  const [editText, setEditText] = useState('');
  const [draggedId, setDraggedId] = useState(null);
  const [darkMode, setDarkMode] = useState(() => localStorage.getItem(THEME_KEY) === 'dark');

  useEffect(() => localStorage.setItem(STORAGE_KEY, JSON.stringify(tasks)), [tasks]);
  useEffect(() => localStorage.setItem(THEME_KEY, darkMode ? 'dark' : 'light'), [darkMode]);

  const selectedKey = formatDateKey(selectedDate);
  const selectedTasks = tasks.filter((task) => task.date === selectedKey);
  const completedCount = tasks.filter((task) => task.date === selectedKey && task.completed).length;
  const monthTaskCount = tasks.filter((task) => {
    const date = new Date(`${task.date}T00:00:00`);
    return date.getFullYear() === currentMonth.getFullYear() && date.getMonth() === currentMonth.getMonth();
  }).length;

  const monthDays = useMemo(() => {
    const firstDay = new Date(currentMonth.getFullYear(), currentMonth.getMonth(), 1);
    const totalDays = new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 1, 0).getDate();
    const cells = Array.from({ length: Math.ceil((firstDay.getDay() + totalDays) / 7) * 7 }, (_, index) => {
      const dayNumber = index - firstDay.getDay() + 1;
      return dayNumber > 0 && dayNumber <= totalDays
        ? new Date(currentMonth.getFullYear(), currentMonth.getMonth(), dayNumber)
        : null;
    });
    return cells;
  }, [currentMonth]);

  const tasksForDate = (date) => tasks.filter((task) => task.date === formatDateKey(date));

  const addTask = () => {
    const text = taskInput.trim();
    if (!text) return;
    const count = Math.max(1, Math.min(365, Number(repeatDays) || 1));
    const seriesId = makeId();
    const created = Array.from({ length: count }, (_, index) => ({
      id: makeId(),
      seriesId,
      text,
      date: formatDateKey(addDays(selectedDate, index)),
      completed: false,
      order: Date.now() + index,
      autoGenerated: index > 0
    }));
    setTasks((previous) => [...previous, ...created]);
    setTaskInput('');
    setRepeatDays('1');
  };

  const toggleTask = (id) => setTasks((previous) => previous.map((task) => task.id === id ? { ...task, completed: !task.completed } : task));

  const removeTask = (id) => setTasks((previous) => {
    const target = previous.find((task) => task.id === id);
    if (!target) return previous;
    return previous.filter((task) => task.id !== id && !(target.seriesId && task.seriesId === target.seriesId));
  });

  const saveEdit = (id) => {
    const text = editText.trim();
    if (!text) return;
    setTasks((previous) => previous.map((task) => task.id === id ? { ...task, text } : task));
    setEditingId(null);
  };

  const moveTask = (fromId, toId) => {
    if (!fromId || fromId === toId) return;
    setTasks((previous) => {
      const dayTasks = previous.filter((task) => task.date === selectedKey);
      const otherTasks = previous.filter((task) => task.date !== selectedKey);
      const fromIndex = dayTasks.findIndex((task) => task.id === fromId);
      const toIndex = dayTasks.findIndex((task) => task.id === toId);
      if (fromIndex < 0 || toIndex < 0) return previous;
      const reordered = [...dayTasks];
      const [moved] = reordered.splice(fromIndex, 1);
      reordered.splice(toIndex, 0, moved);
      return [...otherTasks, ...reordered.map((task, index) => ({ ...task, order: index }))];
    });
  };

  const goToToday = () => {
    setCurrentMonth(new Date(today.getFullYear(), today.getMonth(), 1));
    setSelectedDate(today);
  };

  return (
    <main className={`app-shell ${darkMode ? 'dark' : ''}`}>
      <div className="background-orb orb-one" />
      <div className="background-orb orb-two" />
      <section className="todo-card">
        <header className="app-header">
          <div className="brand"><span className="brand-mark">✓</span><div><p className="eyebrow">PERSONAL PLANNER</p><h1>Daylight</h1></div></div>
          <div className="header-actions"><button className="ghost-button" onClick={goToToday}>Today</button><button className="icon-button" onClick={() => setDarkMode((value) => !value)} aria-label="Toggle dark mode">{darkMode ? '☀' : '☾'}</button></div>
        </header>

        <div className="content-grid">
          <section className="calendar-panel">
            <div className="month-toolbar"><button className="nav-button" onClick={() => setCurrentMonth(new Date(currentMonth.getFullYear(), currentMonth.getMonth() - 1, 1))}>‹</button><div><p className="eyebrow">YOUR SCHEDULE</p><h2>{monthNames[currentMonth.getMonth()]} <span>{currentMonth.getFullYear()}</span></h2></div><button className="nav-button" onClick={() => setCurrentMonth(new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 1, 1))}>›</button></div>
            <div className="weekday-row">{weekdayLabels.map((label) => <div key={label}>{label}</div>)}</div>
            <div className="calendar-grid">{monthDays.map((day, index) => {
              if (!day) return <div key={`empty-${index}`} className="day-box empty" />;
              const key = formatDateKey(day); const dayTasks = tasksForDate(day);
              return <button key={key} className={`day-box ${key === selectedKey ? 'selected' : ''} ${key === todayKey ? 'today' : ''}`} onClick={() => setSelectedDate(day)}><span className="day-number">{day.getDate()}</span><div className="task-dots">{dayTasks.slice(0, 4).map((task) => <i key={task.id} className={task.completed ? 'done' : ''} />)}</div>{dayTasks.length > 4 && <small>+{dayTasks.length - 4}</small>}</button>;
            })}</div>
          </section>

          <aside className="tasks-panel">
            <div className="selected-heading"><div><p className="eyebrow">TASKS FOR</p><h2>{selectedDate.toLocaleDateString(undefined, { weekday: 'long', month: 'short', day: 'numeric' })}</h2></div><div className="progress-ring"><strong>{completedCount}</strong><span>/{selectedTasks.length}</span></div></div>
            <div className="task-entry"><input value={taskInput} onChange={(event) => setTaskInput(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && addTask()} placeholder="What needs to be done?" aria-label="New task" /><button className="primary-button" onClick={addTask}>Add task</button></div>
            <div className="repeat-row"><span>Repeat for next</span><select value={repeatDays} onChange={(event) => setRepeatDays(event.target.value)}><option value="1">Only this day</option><option value="3">3 days</option><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option></select></div>
            <div className="task-list">{selectedTasks.length === 0 ? <div className="empty-state"><span>✦</span><strong>Your day is clear</strong><p>Add a task to get started.</p></div> : [...selectedTasks].sort((a, b) => a.order - b.order).map((task) => <article key={task.id} className={`task-item ${task.completed ? 'completed' : ''}`} draggable onDragStart={() => setDraggedId(task.id)} onDragOver={(event) => event.preventDefault()} onDrop={() => moveTask(draggedId, task.id)}><button className="check-button" onClick={() => toggleTask(task.id)} aria-label="Complete task">{task.completed ? '✓' : ''}</button>{editingId === task.id ? <input className="edit-input" autoFocus value={editText} onChange={(event) => setEditText(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') saveEdit(task.id); if (event.key === 'Escape') setEditingId(null); }} onBlur={() => saveEdit(task.id)} /> : <span className="task-text">{task.text}{task.autoGenerated && <small> recurring</small>}</span>}<div className="task-actions"><button onClick={() => { setEditingId(task.id); setEditText(task.text); }} aria-label="Edit task">✎</button><button onClick={() => removeTask(task.id)} aria-label="Delete task">×</button></div></article>)}</div>
            <footer className="tasks-footer"><span>{monthTaskCount} tasks this month</span><span>⋮⋮ drag to reorder</span></footer>
          </aside>
        </div>
      </section>
    </main>
  );
}

export default App;
